name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-pr:
    name: Validate PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
          disallowScopes: |
            release
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.

      - name: Validate branch naming
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Validating branch name: $BRANCH_NAME"

          # Check if branch follows conventional naming
          if [[ ! "$BRANCH_NAME" =~ ^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|hotfix)/ ]]; then
            echo "❌ Branch name should follow the pattern: type/description"
            echo "Valid types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, hotfix"
            echo "Example: feat/add-voice-generation or fix/database-connection"
            exit 1
          fi

          echo "✅ Branch name follows conventional pattern"

      - name: Check for breaking changes
        run: |
          echo "Checking for potential breaking changes..."

          # Check if any public API files have been modified
          if git diff --name-only origin/main...HEAD | grep -E "(src/voiceover_mage/main\.py|src/voiceover_mage/__init__\.py|src/voiceover_mage/core/)" > /dev/null; then
            echo "⚠️  Public API files have been modified. Please ensure backward compatibility."
            echo "Modified files:"
            git diff --name-only origin/main...HEAD | grep -E "(src/voiceover_mage/main\.py|src/voiceover_mage/__init__\.py|src/voiceover_mage/core/)"
          else
            echo "✅ No public API changes detected"
          fi

      - name: Validate PR size
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | wc -l)
          ADDITIONS=$(git diff --stat origin/main...HEAD | tail -1 | grep -o '[0-9]\+ insertions' | grep -o '[0-9]\+' || echo "0")
          DELETIONS=$(git diff --stat origin/main...HEAD | tail -1 | grep -o '[0-9]\+ deletions' | grep -o '[0-9]\+' || echo "0")

          echo "PR Statistics:"
          echo "📁 Files changed: $CHANGED_FILES"
          echo "➕ Lines added: $ADDITIONS"
          echo "➖ Lines deleted: $DELETIONS"

          if [ "$CHANGED_FILES" -gt 50 ]; then
            echo "⚠️  Large PR detected ($CHANGED_FILES files). Consider breaking it into smaller PRs for easier review."
          fi

          if [ "$ADDITIONS" -gt 1000 ]; then
            echo "⚠️  Large number of additions ($ADDITIONS lines). Consider breaking it into smaller PRs."
          fi